export const PATH_IMAGES = {
    admissions_banner: 'assets/images/banner-admissions.png.webp',
    top_1: 'assets/images/top_1.png',
    top_2: 'assets/images/top_2.png',
    top_3: 'assets/images/top_3.png',
    top_4: 'assets/images/top_4.png',
    course_1: 'assets/images/course_1.jpg.webp',
    course_2: 'assets/images/course_2.jpg.webp',
    course_3: 'assets/images/course_3.jpg.webp',
    benefit_1: 'assets/images/benefit_1.png',
    benefit_2: 'assets/images/benefit_2.png',
    benefit_3: 'assets/images/benefit_3.png',
    benefit_4: 'assets/images/benefit_4.png',
    benefit_5: 'assets/images/benefit_5.png',
    benefit_6: 'assets/images/benefit_6.png',
    partner_1: 'assets/images/partner_1.jpg.webp',
    partner_2: 'assets/images/partner_2.jpg.webp',
    partner_3: 'assets/images/partner_3.jpg.webp',
    partner_4: 'assets/images/partner_4.jpg.webp',
    partner_5: 'assets/images/partner_5.webp',
    partner_6: 'assets/images/partner_6.jpg.webp',
    login: 'assets/images/login-image.jpg',
    avatarDefault: 'assets/images/avatar_default.jpg',
}